### ISSUE TITLE
box circulate

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#140]
figure needs to be created.

most common use case: "balance the wave and box circulate"

# Parameters
- who (the walker, not the looper)
- balances (defaults to true)
- direction: (defaults to clockwise)
- beats

c.f. http://lists.sharedweight.net/pipermail/callers-sharedweight.net/2014-November/016820.html

**Comment by cranhandler** [comment]
Allison to enter

Surfing the Set improper by Bob Isaacs Richard Alan Fisher

A1: Neighbor Bal and swing
A2: circle L 3/4, partner swing
B1: with partner Prom across set, women do si do 1.5 to face out in long
wavy line.
B2: balance, circulate (men cross women loop)  balance and circulate (women
cross men loop to new neighbor)
