### ISSUE TITLE
star promenade

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#143]
Star promenade figure needs a 'who' for 'who is in the center'. 

star promenade left once for 8 (gentlespoons once around, scoop up your partner for)
	butterfly whirl for 8

**Comment by dcmorse** [comment]
c.f. Truffles for Breakfast for a ladles star promenade

**Comment by dcmorse** [comment]
@cranhandler once this fix is deployed, please adjust your dances:

- [ ] Allison Wonderland star promenade left once
- [ ] Caveman gentlespoons star promenade left 1/2
