### ISSUE TITLE
gate

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#144]
Parameters 

Who:
Whom:
Final facing direction:

 	ones Back_Up_Twos_Gate_Ones 

http://contradb.com/dances/60

**Comment by dcmorse** [comment]
final facing directions: {in, out, up, down}

**Comment by dcmorse** [comment]
Ended up with parameters:
- who
- gate_facing
- beats

Waiting on an actual dance...

**Comment by dcmorse** [comment]
Hey, Jefferson's Remorse uses a gate http://contradb.com/dances/60

**Comment by cranhandler** [comment]
Well color me absent-minded.

**Comment by dcmorse** [comment]
If we say "twos gate ones", then the twos are pivoting in place, and the ones are walking long distances around the ones, right?

**Comment by dcmorse** [comment]
No sooner do I deploy, than I find a notation ambiguity:

If I say "gentlespoons gate ladles", then it's not clear which ladle a given gentlespoon is gating. It should be "gentlespoons gate partners" or "gentlespoons gate neighbors".
If I say "ones gate twos" then it's unambiguous thanks to our oppressive heteronormative worldview that G1 gates L2 and L1 gates G2, but it would be less ambiguous to say "ones gate neighbors" or "ones gate same roles".

**Comment by dcmorse** [comment]
create new chooser: `chooser_pairs_or_ones_or_twos`, so that Linda Leslie is happier with http://contradb.com/dances/96. And ContraDB starts to assume dances are about gentlespoons dancing with ladles. It had been so innocent. :(
