### ISSUE TITLE
Autogenerate dance stompiness ratings

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#156]
compute number of dance balances
display it in dance tables
either use the letter 'b' or glyphicon-glyphicon-flash

**Comment by cranhandler** [comment]
Display these as I am crafting a program.

**Comment by dcmorse** [comment]
In branch `stompiness` 3a3f80cd9e78cc016e29cfe683c7d92eda346b5e you see the fraction of the dance where someone is balancing. @cranhandler @djpohly 
![stompiness](https://user-images.githubusercontent.com/10550086/28448323-cd9c78ca-6d9c-11e7-8cf2-de1720b3c902.png)

Deployment TODO:
- [ ] make sure stompiness handles whatever crappy json is thrown at it.
