### ISSUE TITLE
pass by

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#158]
`Across the Ohio` needs a `pass by`.  It seems similar to 'pass through', but for 2 people and not a progression. I think we can just clone `pull by for 2` and have a functional move in short order. 

- used in http://contradb.com/dances/48 as 'cross over'
- used in http://contradb.com/dances/69 as 'pass by'

**Comment by dcmorse** [comment]
- [ ] deploy me
- [ ] add dances

**Comment by dcmorse** [comment]
I need 'pass by' for four dancers too. If I have that I can decompose a hey into 'pass by's:

1. ladles pass by right
2. neighbors pass by left
3. gentlespoons pass by right
&c.

**Comment by cranhandler** [comment]
This ought to be 4 beats by default, http://contradb.com/dances/115 , http://contradb.com/dances/116

**Comment by dcmorse** [comment]
It can be padded to 4 beats, but it really only takes 2 beats. Cary Ravitz puts a pull-by at 2 beats (http://www.dance.ravitz.us/chor.php). A half a hey is three `pass by`s in sequence in 8 beats, which is closer to 2 beats a piece than to 4 beats a piece. Given that it only takes about 2 beats, doesn't it make sense to make the padding explicit?

**Comment by cranhandler** [comment]
Sure, but the last three in a row I entered were for four, just collecting
default data.

Labels:probably wontfix
