### ISSUE TITLE
roll away

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#176]
tweak parameters to match gate
maybe garbage collect param_role because they seem like bad thinking.

**Comment by cranhandler** [comment]
Did we intentionally eliminate 'along / across' as a parameter for this? see http://contradb.com/dances/126 with excessive in-line notes

**Comment by dcmorse** [comment]
Yeah, I feel like we did. That's a dance with a large number of confusing roll aways, so in-line notes are just the thing to make it clear. [Most uses are unambiguous](http://contradb.com/figures/roll-away), and so we don't need to denormalize our figure encoding just for this one dance.
