### ISSUE TITLE
mad robin

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#180]
Current issue: `who` needs to allow more than just 'gentlespoons' and 'ladles'.

**Comment by dcmorse** [comment]
Changed `who` to accept any pair not just role (gentlespoons or ladles).

**Comment by cranhandler** [comment]
Mad Robin circling the default number of times does not fill in a 'beats'

(suggest circling 1 time for 8 beats),

**Comment by dcmorse** [comment]
Yeah, it takes 6 beats but is frequently shoe-horned into 8 beats by people not named "Carey Ravitz". But if you dance it, it's 6 beats. The conclusion was to leave it explicitly undefined (which took some significant work to implement), to force the user to make a conscious decision. 

It's not a very ContraDB way to do things, is it. 

I think you can find the history of this if you look back in the figure's issue.
