### ISSUE TITLE
custom yucky

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#202]
- [ ] @cranhandler : remove the last two instances from the DB
- [ ] @dcmorse : remove the figure from contradb

**Comment by cranhandler** [comment]
I feel dissatisfied with the implementations of the moves represented in Apples and Concord Grapes (pass through to ocean wave would solve this) and in Huckleberry Friend (turn as couples would solve this).

I have turned them into 'custom' so you can delete 'custom yucky' but FWIW I think they both represent failings in the dance editor to describe fairly common and simple figures, and to just mark them 'custom' and call that good forever feels disingenuous.

**Comment by dcmorse** [comment]
I hear ya, @cranhandler. You want better encodings of those figures.

**Comment by dcmorse** [comment]
Yee Haw!!! `custom yucky` is **g.o.n.e!!!**
