### ISSUE TITLE
Rory O'Moore

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#205]
When unchecking 'bal' in Rory O'Moore, I prefer the beat count to drop from the default 8 to 4.

Example is http://contradb.com/dances/124 which has the 'everybody balance' occupying the first 4 beats.

**Comment by cranhandler** [comment]
Right now, "everyone" and "centers" are supported---I need 'ladles' to be an option (presumably also gents) in the case of long lines. 

http://contradb.com/dances/124 needs to be updated from custom notes when this feature is supported

**Comment by cranhandler** [comment]
http://contradb.com/dances/109 needs the same "ladles" support as /124, although instead of long lines, Ladles are just spinning two places to their partner.

Right now, "everyone" and "centers" are supported---I need 'ladles' to be an option (presumably also gents)

**Comment by dcmorse** [comment]
@cranhandler you have a lot of dances you may now update to your preferred method.

Also @cranhandler, I want to draw your attention to the fact that when you check the "balance" checkbox, and select someone other than `everyone`, it's not like it prints `ladles balance and Rory O'Moore`, it prints `balance and ladles Rory O'Moore`. You've been putting the balance on another line, and I think the figure is smart enough (and commonly enough balance-prefixed) that I'd want it to be all on one line. Thoughts?

Options are now:
- everyone
- ladles
- gentlespoons
- centers
- ones
- twos

I thought about including
- first corners
- second corners
but the practical person in me won out, on the grounds that 'centers' would actually be the cleaner call in this situation.
