### ISSUE TITLE
Parameter terminology pass through

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#207]
as in http://www.contradb.com/dances/125 , 'pass through' parameters are 
across the set
up & down the set 
[...]

I motion that 
across the set
along the set

make a better, more understandable pair of opposites.

**Comment by dcmorse** [comment]
Okay, I'm in. I felt like they were both two syllable a-words, and I'm
still worried they'll sound like each other to people with bad hearing.

**Comment by dcmorse** [comment]
changes UI for the following moves:

- chain
- hey
- pass through
- cross trails
- promenade
- pull by for 4
- right left through
