### ISSUE TITLE
configure mailer on production server

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#21]
People lose their passwords, and we have to send them password reminders. To do that, we've gotta have a way to send mail, either by setting up a mail server on this machine (meh), or by finding some web service that'll let us mail through them. Also, rails has to be configured to send mail in https://github.com/dcmorse/contra/blob/master/config/environments/production.rb . If you're interested in working on this and you're someone I know, let me know, let's talk it over, and I'll send you the passwords and such.

**Comment by strongjz** [comment]
Have you thought about using a 3rd party service? http://mailchimp.com/

**Comment by dcmorse** [comment]
@strongjz 
To send automated password reminders you'd use mailchimp? Aren't they geared towards corporate newsletters? Doesn't it cost money?

Fifteen years ago I configured sendmail to send mail from a server. It seemed super-insecure, and I was always fearing that I was going on vacation and leaving a spam sending zombie mailserver to my ISP to deal with. Is unix mail server configuration still terrible?

Literally all I need is to route outgoing email for password reminders.

**Comment by dcmorse** [comment]
- blocked port 25
- configured postfix locally
- sending out gets an error message
- haven't done anything with MX records yet

**Comment by dcmorse** [comment]
I abandoned local changes when installing name/passwords on postfix was going down a slippery slope of complexity. 

Ended up integrating with gmail, which I guess is nice because now I have a gmail account to conduct official business with. 

Good riddance to this almost 2 year old issue!

8d08c8a81f05cdaa3fdd587edefce8a26189f862
