### ISSUE TITLE
Pull by for 2

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#219]
# Parameters
- who
- balance
- hand
- beats

@chetgray noticed in [Four Have Spring](http://contradb.com/dances/150/) that there was no `partners` option in `pull by for 2`

**Comment by dcmorse** [comment]
Wait, that'd be a `pull by for 4`. Closing this and continuing discussion in [Pull by for 4](https://github.com/dcmorse/contra/issues/142)

**Comment by cranhandler** [comment]
I would like to re-open this issue, pull-by for 2 needs a neighbors option, to support http://contradb.com/dances/203

Will be better still with 1st neighbor, 2nd neighbor, 3rd neighbor

**Comment by dcmorse** [comment]
I agree with your reasoning. On October 22 I agreed and I put all the information about the pull-by rewrite into the discussion of Pull by for 4, so that we don't have 2 places to store the same information. There's a link above.
