### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#231]
If we ever get to use avatars, this is adminisaur's

http://www.dinosaurjungle.com/nova_ankylosaurus2.png

source

http://www.dinosaurjungle.com/dinosaur_species_ankylosaurus_pictures.php

**Comment by dcmorse** [comment]
Duplicate of https://github.com/dcmorse/contra/issues/68
which I closed after 2 years due to lack of assistance.
