### ISSUE TITLE
leaving the minor set

### ISSUE THREAD

**Issue by finnygal** [dcmorse/contra#232]
I have several dances that require the dancers to briefly leave the minor set. It would be nice to have the option to say "next" neighbor or "former" neighbor in the drop down. This also applies to double progression dances when you need to move to a new neighbor in the middle of the dance. Right now the only option is to add that to the notes which is a tad awkward when reading.

**Comment by dcmorse** [comment]
I hear you. Lemme think about how to do it.

**Comment by dcmorse** [comment]
Cary Ravitz writes:

> I was looking at ContraDB - Dar Trek. First, it appears I can't fix it, only create a variation. Also, "who" needs to include second neighbors, and for other dances third and fourth neighbors, and second shadows. And it couldn't hurt to have a way of specifying a progression - could be just a symbol that means look out of your current set.

I write:

> so do I understand right that there's demand for 'next neighbor', 'next next neighbor', 'next next next neighbor', and 'previous neighbor'?
> What's the difference between "shadow" and "second shadow"? Regular 'shadow' is the partner of the person dancing one upstream or downstream of me, but which one? And it flip-flops if I change roles?

Cary Ravitz writes:
> If you are a man in Becket formation, there is a shadow in your left hand and a shadow two places to the right of your partner, and maybe more up and down the line. I use first shadow to mean the first one that you meet, and so on. It's not a specific position, but depends on the dance. See "Me and My Shadows" for a worst case notation problem.
> "3,33" uses next neighbors. Dar Trek is complicated enough that I prefer to use first neighbors and second neighbors. Next isn't descriptive when you do more than one figure with the next neighbor. Some dances use current and previous neighbors.

I write:

> One thing I'm chewing on is this: people searching for 'neighbor swing' aren't going to want to discriminiate between 'first neighbor' and 'second neighbor' ... or are they?

> As for the progression symbol - there's the 0-beat 'figure' called "progress", which is intended to signify reassigning the meaning of 'neighbor' to a new dancer. I thought about letting it take an argument of 'next' or 'previous', but decided to wait for more insight. It's not been wildly successful - I'm the only one using it, I think.

Could the progress figure (or some other sentinel) denote zones on how to render 'neighbor'? Like normally render `neighbor` as 'neighbor', but after a progress +1, render `neighbor` as 'second neighbor`, and after a progress -1, render `neighbor` as 'old neighbor'?

**Comment by cranhandler** [comment]
For what it's worth in the meantime, I have been encoding "to neighbor" and adding "NEXT neighbor" in the note. Not the ideal long-term solution, but you'll see some dances coded this way until we have a full treatment of the issue.

**Comment by cranhandler** [comment]
See http://contradb.com/dances/204 for a robust case for needing 'next neighbor' to be a dancer type, or 'neighbor 2' and 'neighbor 3' 

maybe say next neighbor by default, but then once someone elects to include a neighbor 3, all 'nexts' get renamed to '2'

**Comment by cranhandler** [comment]
http://contradb.com/dances/203
I prefer the nomenclature that's in the notes here.

**Comment by dcmorse** [comment]
### draft plan
Change encoding of `chooser_dancers` et al to go from a simple string - e.g. `'neighbors'` - to an array of the form `['neighbors', '1st']`. In the most common case, the second array element will simply be the empty string, which is logically equivalent to `'1st'`. Values to include

- ''
- '1st'
- '2nd'
- '3rd'
- '4th'
- 'previous'

Only show this menu on `neighbor` or `shadow`. Maybe shadow should show a smaller menu, if it's easy. 

- [ ] change every figure stringifying view that senses the output of a `chooser_dancer`. 
- [ ] change figure search to accomodate this compound widget. 

#### Time Estimate: 20 hours!

**Comment by cranhandler** [comment]
This only misses the finer-point that 'if only 1st and 2nd exist in a dance, caller will want to see `next` in place of `2nd`

**Comment by dcmorse** [comment]
### the 'menu explosion' implementation strategy [4]

- add '2nd neighbor', '3rd neighbor', '4th neighbor', 'old neighbor', '2nd shadow' to menus.
- on figure search, add additionally 'any neighbor' and 'any shadow', which would be special-cased in the filters rails side

Still would be enormously less hairy than the 'composite' strategy.

**Comment by dcmorse** [comment]
### the 'progress-sensitive-neighbor' implementation strategy [?]
- add '2nd shadow' and 'any shadow' as per [menu explosion strategy](https://github.com/dcmorse/contra/issues/232#issuecomment-350273273)
- when rendering 'neighbor', look at how many progressions have preceded it in the dance:
  - zero progressions: 'neighbor'
  - one progression: 'next neighbor' or '2nd neighbor'
  - two progressions: '3rd neighbor'
  - _n_ progressions: '_n+1_th neighbor'

#### Pros: 
- generalizes to support 6th neighbor without undue menu clutter. 
#### Cons:
- we've pretty much determined that people don't think like this. They wanna see "next neighbor" in the who menus. "Don't make me think". 
- makes figure rendering dependant on the rest of the dance context (but next/2nd neighbor rendering will do that in all implementation strategies, so this is not a con)
