### ISSUE TITLE
SEARCH

### ISSUE THREAD

**Issue by dcmorse** [dcmorse/contra#42]
Search of dances based on various queries.
This will eventually replace the "dances" index view, because there will be too many dances.

**Comment by strongjz** [comment]
Gems for everything! https://rubygems.org/search?utf8=%E2%9C%93&query=search

looks like https://rubygems.org/gems/pg_search and https://rubygems.org/gems/meta_search are the top downloads

**Comment by dcmorse** [comment]
Awesome!

**Comment by dcmorse** [comment]
# Use Case: finding dances with or without certain moves
We're at a dance hall full of 50 new dancers. It's too big and too hectic to teach courtesy turns. We need to find dances that don't have 'chain' or 'right left through'. Index cards go flying as we begin a manual, brute-force search for dances meeting those criteria.

# Use Case: finding figures with or without a specific parameter value
You really want a dance with a full hey. Right now you click the 'Figures' link, click 'hey', and visually scan for dances with a full hey. We don't want the list cluttered with cruddy half heys!

# Server Side Query
Here's a rough search for a dances without 'right left through' or 'chain':
```
Dance.all.to_a.select {|d| d.figures.none? {|f| f['move'].in? ['right left through', 'chain']}}.map(&:title)
```

And here's a rough search for dances that circle right:
```
Dance.all.to_a.select {|d| d.figures.any? {|f| f['move'] == 'circle' && !f['parameter_values'][0]}}.map(&:title)
```
Implementation note: the first parameter to circle is the direction of the circle - it's true for a circle left, and false for a circle right. That is drawn from `figures.es6`.
 
# User Interface
The user is not going to write these kinds of ruby blocks. We need a DSL or clickable ui features....

**Comment by dcmorse** [comment]
In Advanced Figure Search Implementation Plan Phase II, when you click on 'some', the search box accordions down, and you specify exactly which characteristics of the figure you care about. In this picture, the user only wants to match dances with a gents chain, and doesn't care to see anything about ladies chains.

Unlike text-based dance indexing, ContraDB knows contra, so the 'some'-click accordion fields are on-point for every figure. You'll be able to search for same-role swings, or roll-aways without half sashays, or clockwise half poussettes. The implementation on this part is a little further down the road. 

![some](https://user-images.githubusercontent.com/10550086/27572351-131d1c08-5ad1-11e7-88c1-48db9842195c.jpg)

**Comment by dcmorse** [comment]
It's not optimal to just click an "+Add" butotn at the end of the list of search criteria. There's a lot of paranthitization that's not expressible with that. 

What we really want is the ability to click "split" on a figure node, and subdivide it into two criteria separated by an 'and' or 'or' or 'then'. This creates a tree-like combination of figure nodes. I sure hope query params are up for deserialzing that.

**Comment by dcmorse** [comment]
meeting minutes
# Filter
- search box searches title, choreographer, dance notes, figure notes (various weights)
- formations (checkboxes)
- index sliders for all indices
- require figure (and select parameters for that figure or select follow-on-figure)
- exclude figure (and select parameters for that figure or select follow-on-figure)

**Comment by dcmorse** [comment]
# BOOM!
