### ISSUE TITLE
turn drop-down menu is set to default selection upon edit

### ISSUE THREAD

**Issue by chetgray** [dcmorse/contra#43]
### Steps to reproduce

1. Create a new dance or edit an existing dance.
2. Select a move that cares about rotations or places (`do_si_do`, `see_saw`, `allemande_right`, `allemande_left`, `gypsy_right_shoulder`, `gypsy_left_shoulder`, `circle_left`, `circle_right`, `star_left`, `star_right`).
3.  Select a turn amount other than the default for that move (*e.g.* something **other than** "once" for `do_si_do` or `see_saw`, "1½" for `allemande_*` or `gypsy_*`, "3 places" for `circle_*`, or "4 places" for `star_*`).
4.  Save the dance.

    Observe that the correct turn amount is displayed in the dance view.
6.  Edit the dance.

#### Expected results

The non-default turn amount previously selected is already selected from the turn drop-down menu.

#### Actual results

The turn drop-down menu has returned to the default selection

### Notes

If an existing dance already has non-default turn amounts saved, copying it (which goes to the edit page) also reproduces the bug. See http://contradb.com/dances/32 and http://contradb.com/dances/33 as examples.

**Comment by dcmorse** [comment]
https://github.com/dcmorse/contra/commit/09388e04dc9ddf91a462eef058ddb527b9038763
